# Generated by Django 5.1.3 on 2024-12-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.IntegerField()),
                ('nhabitacion', models.IntegerField()),
                ('Estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('correo', models.TextField()),
                ('contraseña', models.CharField(max_length=50)),
                ('piso', models.IntegerField()),
                ('nhabitacion', models.IntegerField()),
                ('Estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=50)),
                ('contraseña', models.CharField(max_length=80)),
                ('Ciudad', models.CharField(default='N/A', max_length=30)),
                ('rol', models.CharField(default='Cliente', max_length=20)),
            ],
        ),
    ]
