# Generated by Django 5.1.3 on 2024-12-01 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0002_alter_reservas_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='Estado',
        ),
    ]
